name: OrangeFox
on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'OF branch'
        required: true
        default: '12.1'
        type: choice
        options:
        - '14.1'
        - '12.1'
        - '11.0'
      DEVICE_TREE:
        description: 'DT git'
        required: true
        default: 'https://github.com/cachiusa/orangefox_device_xiaomi_veux'
      DEVICE_TREE_BRANCH:
        description: 'DT branch'
        required: true
        default: 'staging'
      DEVICE_PATH:
        description: 'DT path'
        required: true
        default: 'device/xiaomi/veux'
      DEVICE_NAME:
        description: 'Device'
        required: true
        default: 'veux'
      USE_CCACHE:
        description: Use ccache
        type: boolean
        required: true
        default: true

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
              
    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set swap
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24
      
    - name: Build environment
      run: |
        echo "Installing..."
        sudo apt-get update
        sudo apt-get install git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 \
        x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

        echo "Installing repo"
        sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo chmod a+rx /usr/local/bin/repo


    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      if: github.event.inputs.USE_CCACHE == 'true'
      with:
        max-size: "10G"
      
    - name: repo sync
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
        cd ${GITHUB_WORKSPACE}/OrangeFox
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git clone https://gitlab.com/OrangeFox/sync.git -b master
        cd sync
        ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}

    - name: Show free space
      run: df -h

    - name: Device tree
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }} 
        cd ${{ github.event.inputs.DEVICE_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

        cd -
        set +e
        source build/envsetup.sh
        sed -i '$ a CONFIG_KSU=y' kernel/xiaomi/sm6375/arch/arm64/configs/veux_defconfig

    - name: Build
      run: |
        set +e
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        
        if [[ ${{ github.event.inputs.USE_CCACHE }} == true ]]; then
          export USE_CCACHE=1
          export CCACHE_EXEC=/usr/bin/ccache
          sed -i 's/return sandboxConfig\.working/return false/g' build/soong/ui/build/sandbox_linux.go
        fi

        source build/envsetup.sh
        lunch twrp_veux-eng && mka adbd vendorbootimage
        
        export TWRP_BUILD_BOOT_IMAGE=1
        source build/envsetup.sh
        lunch twrp_veux-eng && mka adbd bootimage

    - name: Set Release name
      run: |
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        mgb=vendor/recovery/tools/magiskboot
        mkdir tempo
        cd tempo
        for i in $(find ../out/target/product/veux -name "OrangeFox-*.img"); do
            $mgb unpack $i
            if [[ $i == *"vendor_boot"* ]]; then
                mv ramdisk.cpio vendor_boot.cpio
            else
                mv ramdisk.cpio boot.cpio
            fi
            $mgb cleanup
        done
        git clone https://gitlab.com/1f1e33/android/AnyKernel3.git -b beta
        mv *.cpio AnyKernel3/recovery
        cd AnyKernel3
        zip -r9 ../the_prince.zip . -x "**.git*" "*placeholder"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/tempo/the_prince.zip
        name: ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          ## OrangeFox Recovery Build - Unofficial
          Build: fox_${{ github.event.inputs.MANIFEST_BRANCH }}
          Device: [Device Tree/Branch](${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ github.event.inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
